---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r unzip file, echo = TRUE }
data<-read.csv("activity.csv")
head(data)
str(data)
summary(data)
```

#data$date<-as.Date(data$date)
#data$date<-transform(data, date=as.Date(date))


## What is mean total number of steps taken per day?
```{r total steps per day, echo = TRUE }
require(dplyr) #needed for summarize command
agg_data<-summarize(group_by(data,date),steps=sum(steps))
agg_data<-transform(agg_data, date=factor(date))
head(agg_data)
hist(agg_data$steps,main="Steps per Day",xlab="Total Number of Steps per Day",ylim = c(0,30),col="orange")
#see mean and median
summary(agg_data)
#alternative way to see mean and median
mean(agg_data$steps,na.rm = T)
median(agg_data$steps,na.rm = T)
```

## What is the average daily activity pattern?
```{r average daily activity, echo = TRUE }
mean_data<-summarize(group_by(data,interval),steps=mean(steps,na.rm=T))
with(mean_data,plot(interval,steps, type="l"))
#which interval has max steps
mean_data[which.max(mean_data$steps),]
```


## Imputing missing values
```{r impute missing values with MICE, echo = TRUE }
install.packages("mice",repos = "http://cran.us.r-project.org")
library(mice)
#impute using random sample from subject's entire observed measurements. Most reasonable imputation. generate 1 dataset from 500 iterations.
datat<-data
imp<- mice(data = datat, m = 1, method = c("sample","",""), maxit = 500)
data_comp <- complete(imp)
agg_data_comp<-summarize(group_by(data_comp,date),steps=sum(steps))
#agg_data<-transform(agg_data, date=factor(date))
hist(data_comp$steps,main="Steps per Day (MICE Imputed)",xlab="Total Number of Steps per Day", col="blue")
```


```{r impute missing values with KNN, echo = TRUE }
install.packages("VIM",repos = "http://cran.us.r-project.org")
library("VIM")
#impute using k-nearest neighbor (KNN)- this is akin to taking the average of the interval in which there is an NA.Less reasonable imputation method considering the non-NAs could be mere outliers. random sampling from entire available [observed] population of steps is more sound. 
imp2<-kNN(datat, variable = c("steps"))
agg_imp2<-summarize(group_by(imp2,date),steps=sum(steps))
#agg_data<-transform(agg_data, date=factor(date))
hist(agg_imp2$steps,main="Steps per Day (KNN Imputed)",xlab="Total Number of Steps per Day", col="blue",ylim=c(0,30))
```


## Are there differences in activity patterns between weekdays and weekends?
```{r  differences in activity patterns between weekdays and weekends, echo = TRUE }
#pull days from imp2$date and if they are either 0 or 6 then it is a weekend, else it is a weekday. store in new col 'day'
imp2$day <- ifelse(as.POSIXlt(imp2$date)$wday %in% c(0,6), 'weekend', 'weekday')
agg_imp2_day<-summarize(group_by(imp2,interval,day),steps=mean(steps))
library(ggplot2)
g<-ggplot(agg_imp2_day,aes(interval,steps))
g+geom_line() + facet_grid(day~.) + ggtitle(expression("Activity Patterns between Weekdays and Weekends"))
```